services:
  ifr-cpu:
    image: insightface-rest-cpu:${IFR_VERSION}
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile_cpu
    hostname: ifr
    env_file:
      - cpu.env
    volumes:
      - insightface-models:/models
    ports:
      - 18081:18080
      
volumes:
  insightface-models:
